{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-secret
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: {{ .Values.secret.type | default "Opaque" }}
data:
  {{- if .Values.secret.data }}
  {{- $_ := set . "secretData" .Values.secret.data }}
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
stringData:
  {{- if .Values.secret.stringData }}
  {{- toYaml .Values.secret.stringData | nindent 2 }}
  {{- end }}
{{- end }}
