---
# Main Application Service
apiVersion: v1
kind: Service
metadata:
  name: ${NAME}-api
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: ${NAME}
    app.kubernetes.io/component: application
    app.kubernetes.io/managed-by: gcp-marketplace
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: https
    port: 443
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: ${NAME}
    app.kubernetes.io/component: application

---
# Admin Service
apiVersion: v1
kind: Service
metadata:
  name: ${NAME}-admin
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: ${NAME}
    app.kubernetes.io/component: admin
    app.kubernetes.io/managed-by: gcp-marketplace
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8081
    protocol: TCP
  selector:
    app.kubernetes.io/name: ${NAME}
    app.kubernetes.io/component: application

---
# Metrics Service
apiVersion: v1
kind: Service
metadata:
  name: ${NAME}-metrics
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: ${NAME}
    app.kubernetes.io/component: metrics
    app.kubernetes.io/managed-by: gcp-marketplace
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 9090
    targetPort: metrics
    protocol: TCP
  selector:
    app.kubernetes.io/name: ${NAME}
    app.kubernetes.io/component: application
